/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/PingPongCode/gomap3d/cpp */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */




/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


/* Return type for ENU2AER */
struct ENU2AER_return {
	GoFloat64 r0; /* az */
	GoFloat64 r1; /* el */
	GoFloat64 r2; /* srange */
};
extern struct ENU2AER_return ENU2AER(GoFloat64 e, GoFloat64 n, GoFloat64 u);

/* Return type for AER2ENU */
struct AER2ENU_return {
	GoFloat64 r0; /* e */
	GoFloat64 r1; /* n */
	GoFloat64 r2; /* u */
};
extern struct AER2ENU_return AER2ENU(GoFloat64 az, GoFloat64 el, GoFloat64 srange);

/* Return type for AER2ECEF */
struct AER2ECEF_return {
	GoFloat64 r0; /* x */
	GoFloat64 r1; /* y */
	GoFloat64 r2; /* z */
};
extern struct AER2ECEF_return AER2ECEF(GoFloat64 az, GoFloat64 el, GoFloat64 srange, GoFloat64 lat0, GoFloat64 lon0, GoFloat64 h0, GoString coordinateSystem);

/* Return type for ECEF2AER */
struct ECEF2AER_return {
	GoFloat64 r0; /* az */
	GoFloat64 r1; /* el */
	GoFloat64 r2; /* srange */
};
extern struct ECEF2AER_return ECEF2AER(GoFloat64 x, GoFloat64 y, GoFloat64 z, GoFloat64 lat0, GoFloat64 lon0, GoFloat64 h0, GoString coordinateSystem);

/* Return type for Geodetic2ECEF */
struct Geodetic2ECEF_return {
	GoFloat64 r0; /* x */
	GoFloat64 r1; /* y */
	GoFloat64 r2; /* z */
};
extern struct Geodetic2ECEF_return Geodetic2ECEF(GoFloat64 lat, GoFloat64 lon, GoFloat64 alt, GoString coordinateSystem);

/* Return type for ECEF2Geodetic */
struct ECEF2Geodetic_return {
	GoFloat64 r0; /* lat */
	GoFloat64 r1; /* lon */
	GoFloat64 r2; /* alt */
};
extern struct ECEF2Geodetic_return ECEF2Geodetic(GoFloat64 x, GoFloat64 y, GoFloat64 z, GoString coordinateSystem);

/* Return type for ECEF2ENU */
struct ECEF2ENU_return {
	GoFloat64 r0; /* e */
	GoFloat64 r1; /* n */
	GoFloat64 r2; /* u */
};
extern struct ECEF2ENU_return ECEF2ENU(GoFloat64 x, GoFloat64 y, GoFloat64 z, GoFloat64 lat0, GoFloat64 lon0, GoFloat64 h0, GoString coordinateSystem);

/* Return type for ENU2ECEF */
struct ENU2ECEF_return {
	GoFloat64 r0; /* x */
	GoFloat64 r1; /* y */
	GoFloat64 r2; /* z */
};
extern struct ENU2ECEF_return ENU2ECEF(GoFloat64 e, GoFloat64 n, GoFloat64 u, GoFloat64 lat0, GoFloat64 lon0, GoFloat64 h0, GoString coordinateSystem);
extern GoFloat64 juliandate(GoFloat64 timestamp);
extern GoFloat64 greenwichsrt(GoFloat64 jd);

/* Return type for ECI2ECEF */
struct ECI2ECEF_return {
	GoFloat64 r0; /* xEcef */
	GoFloat64 r1; /* yEcef */
	GoFloat64 r2; /* zEcef */
};
extern struct ECI2ECEF_return ECI2ECEF(GoFloat64 x, GoFloat64 y, GoFloat64 z, GoFloat64 timestamp);

/* Return type for ECEF2ECI */
struct ECEF2ECI_return {
	GoFloat64 r0; /* xEci */
	GoFloat64 r1; /* yEci */
	GoFloat64 r2; /* zEci */
};
extern struct ECEF2ECI_return ECEF2ECI(GoFloat64 x, GoFloat64 y, GoFloat64 z, GoFloat64 timestamp);

/* Return type for ECEFVel2ECIVel */
struct ECEFVel2ECIVel_return {
	GoFloat64 r0; /* vxEci */
	GoFloat64 r1; /* vyEci */
	GoFloat64 r2; /* vzEci */
};
extern struct ECEFVel2ECIVel_return ECEFVel2ECIVel(GoFloat64 vx, GoFloat64 vy, GoFloat64 vz, GoFloat64 x, GoFloat64 y, GoFloat64 z, GoFloat64 timestamp);

/* Return type for ECIVel2ECEFVel */
struct ECIVel2ECEFVel_return {
	GoFloat64 r0; /* vxEcef */
	GoFloat64 r1; /* vyEcef */
	GoFloat64 r2; /* vzEcef */
};
extern struct ECIVel2ECEFVel_return ECIVel2ECEFVel(GoFloat64 vx, GoFloat64 vy, GoFloat64 vz, GoFloat64 x, GoFloat64 y, GoFloat64 z, GoFloat64 timestamp);

/* Return type for ENUVel2ECEFVel */
struct ENUVel2ECEFVel_return {
	GoFloat64 r0; /* vx */
	GoFloat64 r1; /* vy */
	GoFloat64 r2; /* vz */
};
extern struct ENUVel2ECEFVel_return ENUVel2ECEFVel(GoFloat64 eVel, GoFloat64 nVel, GoFloat64 uVel, GoFloat64 latDeg, GoFloat64 lonDeg);

/* Return type for ECEFVel2ENUVel */
struct ECEFVel2ENUVel_return {
	GoFloat64 r0; /* e */
	GoFloat64 r1; /* n */
	GoFloat64 r2; /* u */
};
extern struct ECEFVel2ENUVel_return ECEFVel2ENUVel(GoFloat64 vx, GoFloat64 vy, GoFloat64 vz, GoFloat64 latDeg, GoFloat64 lonDeg);

/* Return type for AERDeriv2ENUVel */
struct AERDeriv2ENUVel_return {
	GoFloat64 r0; /* e */
	GoFloat64 r1; /* n */
	GoFloat64 r2; /* u */
};
extern struct AERDeriv2ENUVel_return AERDeriv2ENUVel(GoFloat64 R, GoFloat64 azDeg, GoFloat64 elDeg, GoFloat64 dR, GoFloat64 dAzDeg, GoFloat64 dElDeg);

/* Return type for ENUVel2AERDeriv */
struct ENUVel2AERDeriv_return {
	GoFloat64 r0; /* dR */
	GoFloat64 r1; /* dAzDeg */
	GoFloat64 r2; /* dElDeg */
};
extern struct ENUVel2AERDeriv_return ENUVel2AERDeriv(GoFloat64 eVel, GoFloat64 nVel, GoFloat64 uVel, GoFloat64 R, GoFloat64 azDeg, GoFloat64 elDeg);

/* Return type for AERDeriv2ECIVel */
struct AERDeriv2ECIVel_return {
	GoFloat64 r0; /* vx */
	GoFloat64 r1; /* vy */
	GoFloat64 r2; /* vz */
};
extern struct AERDeriv2ECIVel_return AERDeriv2ECIVel(GoFloat64 R, GoFloat64 azDeg, GoFloat64 elDeg, GoFloat64 dR, GoFloat64 dAzDeg, GoFloat64 dElDeg, GoFloat64 latDeg, GoFloat64 lonDeg, GoFloat64 timestamp);

#ifdef __cplusplus
}
#endif
